// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function HostCreate(arg1:main.Host):Promise<main.H>;

export function HostDelete(arg1:string):Promise<main.H>;

export function HostEdit(arg1:main.Host):Promise<main.H>;

export function HostList():Promise<main.H>;

export function WriteHost(arg1:main.Host):Promise<main.H>;
