// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HostCreate(arg1) {
  return window['go']['main']['App']['HostCreate'](arg1);
}

export function HostDelete(arg1) {
  return window['go']['main']['App']['HostDelete'](arg1);
}

export function HostEdit(arg1) {
  return window['go']['main']['App']['HostEdit'](arg1);
}

export function HostList() {
  return window['go']['main']['App']['HostList']();
}

export function WriteHost(arg1) {
  return window['go']['main']['App']['WriteHost'](arg1);
}
